#! /bin/sh

bspc config border_width        3
bspc config window_gap          22

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.5

bspc monitor VGA1 -d I III V
bspc monitor DP1 -d II IV VI 

bspc rule -a Screenkey manage=off

# Float hangouts
bspc rule -a "crx_nckgahadagoaajjgafhacjanaoiihapd" floating=on
bspc rule -a Conky sticky=on manage=off fullscreen=on
bspc rule -a feh floating=on manage=off

compton&
xfce4-panel&
stalonetray&
synergy&
conky -c ~/.config/bspwm/conky-bl&
conky -c ~/.config/bspwm/conky-br&

feh --bg-fill $HOME/.config/bspwm/forest.jpg

