#! /bin/sh

bspc config border_width        3
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.5

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton&
xfce4-panel&
feh --bg-fill $HOME/.config/bspwm/forest.jpg

